<?php
// All countries
// length 252
 return $country_list = array(
    "AF" => array("name" => "Afghanistan", "id" => 1),
    "AX" => array("name" => "Aland Islands", "id" => 2),
    "AL" => array("name" => "Albania", "id" => 3),
    "DZ" => array("name" => "Algeria", "id" => 4),
    "AS" => array("name" => "American Samoa", "id" => 5),
    "AD" => array("name" => "Andorra", "id" => 6),
    "AO" => array("name" => "Angola", "id" => 7),
    "AI" => array("name" => "Anguilla", "id" => 8),
    "AQ" => array("name" => "Antarctica", "id" => 9),
    "AG" => array("name" => "Antigua and Barbuda", "id" => 10),
    "AR" => array("name" => "Argentina", "id" => 11),
    "AM" => array("name" => "Armenia", "id" => 12),
    "AW" => array("name" => "Aruba", "id" => 13),
    "AU" => array("name" => "Australia", "id" => 14),
    "AT" => array("name" => "Austria", "id" => 15),
    "AZ" => array("name" => "Azerbaijan", "id" => 16),
    "BS" => array("name" => "Bahamas", "id" => 17),
    "BH" => array("name" => "Bahrain", "id" => 18),
    "BD" => array("name" => "Bangladesh", "id" => 19),
    "BB" => array("name" => "Barbados", "id" => 20),
    "BY" => array("name" => "Belarus", "id" => 21),
    "BE" => array("name" => "Belgium", "id" => 22),
    "BZ" => array("name" => "Belize", "id" => 23),
    "BJ" => array("name" => "Benin", "id" => 24),
    "BM" => array("name" => "Bermuda", "id" => 25),
    "BT" => array("name" => "Bhutan", "id" => 26),
    "BO" => array("name" => "Bolivia", "id" => 27),
    "BQ" => array("name" => "Bonaire, Sint Eustatius and Saba", "id" => 28),
    "BA" => array("name" => "Bosnia and Herzegovina", "id" => 29),
    "BW" => array("name" => "Botswana", "id" => 30),
    "BV" => array("name" => "Bouvet Island", "id" => 31),
    "BR" => array("name" => "Brazil", "id" => 32),
    "IO" => array("name" => "British Indian Ocean Territory", "id" => 33),
    "BN" => array("name" => "Brunei Darussalam", "id" => 34),
    "BG" => array("name" => "Bulgaria", "id" => 35),
    "BF" => array("name" => "Burkina Faso", "id" => 36),
    "BI" => array("name" => "Burundi", "id" => 37),
    "KH" => array("name" => "Cambodia", "id" => 38),
    "CM" => array("name" => "Cameroon", "id" => 39),
    "CA" => array("name" => "Canada", "id" => 40),
    "CV" => array("name" => "Cape Verde", "id" => 41),
    "KY" => array("name" => "Cayman Islands", "id" => 42),
    "CF" => array("name" => "Central African Republic", "id" => 43),
    "TD" => array("name" => "Chad", "id" => 44),
    "CL" => array("name" => "Chile", "id" => 45),
    "CN" => array("name" => "China", "id" => 46),
    "CX" => array("name" => "Christmas Island", "id" => 47),
    "CC" => array("name" => "Cocos (Keeling) Islands", "id" => 48),
    "CO" => array("name" => "Colombia", "id" => 49),
    "KM" => array("name" => "Comoros", "id" => 50),
    "CG" => array("name" => "Congo", "id" => 51),
    "CD" => array("name" => "Congo, Democratic Republic of the Congo", "id" => 52),
    "CK" => array("name" => "Cook Islands", "id" => 53),
    "CR" => array("name" => "Costa Rica", "id" => 54),
    "CI" => array("name" => "Cote D'Ivoire", "id" => 55),
    "HR" => array("name" => "Croatia", "id" => 56),
    "CU" => array("name" => "Cuba", "id" => 57),
    "CW" => array("name" => "Curacao", "id" => 58),
    "CY" => array("name" => "Cyprus", "id" => 59),
    "CZ" => array("name" => "Czech Republic", "id" => 60),
    "DK" => array("name" => "Denmark", "id" => 61),
    "DJ" => array("name" => "Djibouti", "id" => 62),
    "DM" => array("name" => "Dominica", "id" => 63),
    "DO" => array("name" => "Dominican Republic", "id" => 64),
    "EC" => array("name" => "Ecuador", "id" => 65),
    "EG" => array("name" => "Egypt", "id" => 66),
    "SV" => array("name" => "El Salvador", "id" => 67),
    "GQ" => array("name" => "Equatorial Guinea", "id" => 68),
    "ER" => array("name" => "Eritrea", "id" => 69),
    "EE" => array("name" => "Estonia", "id" => 70),
    "ET" => array("name" => "Ethiopia", "id" => 71),
    "FK" => array("name" => "Falkland Islands (Malvinas)", "id" => 72),
    "FO" => array("name" => "Faroe Islands", "id" => 73),
    "FJ" => array("name" => "Fiji", "id" => 74),
    "FI" => array("name" => "Finland", "id" => 75),
    "FR" => array("name" => "France", "id" => 76),
    "GF" => array("name" => "French Guiana", "id" => 77),
    "PF" => array("name" => "French Polynesia", "id" => 78),
    "TF" => array("name" => "French Southern Territories", "id" => 79),
    "GA" => array("name" => "Gabon", "id" => 80),
    "GM" => array("name" => "Gambia", "id" => 81),
    "GE" => array("name" => "Georgia", "id" => 82),
    "DE" => array("name" => "Germany", "id" => 83),
    "GH" => array("name" => "Ghana", "id" => 84),
    "GI" => array("name" => "Gibraltar", "id" => 85),
    "GR" => array("name" => "Greece", "id" => 86),
    "GL" => array("name" => "Greenland", "id" => 87),
    "GD" => array("name" => "Grenada", "id" => 88),
    "GP" => array("name" => "Guadeloupe", "id" => 89),
    "GU" => array("name" => "Guam", "id" => 90),
    "GT" => array("name" => "Guatemala", "id" => 91),
    "GG" => array("name" => "Guernsey", "id" => 92),
    "GN" => array("name" => "Guinea", "id" => 93),
    "GW" => array("name" => "Guinea-Bissau", "id" => 94),
    "GY" => array("name" => "Guyana", "id" => 95),
    "HT" => array("name" => "Haiti", "id" => 96),
    "HM" => array("name" => "Heard Island and McDonald Islands", "id" => 97),
    "VA" => array("name" => "Holy See (Vatican City State)", "id" => 98),
    "HN" => array("name" => "Honduras", "id" => 99),
    "HK" => array("name" => "Hong Kong", "id" => 100),
    "HU" => array("name" => "Hungary", "id" => 101),
    "IS" => array("name" => "Iceland", "id" => 102),
    "IN" => array("name" => "India", "id" => 103),
    "ID" => array("name" => "Indonesia", "id" => 104),
    "IR" => array("name" => "Iran, Islamic Republic of", "id" => 105),
    "IQ" => array("name" => "Iraq", "id" => 106),
    "IE" => array("name" => "Ireland", "id" => 107),
    "IM" => array("name" => "Isle of Man", "id" => 108),
    "IL" => array("name" => "Israel", "id" => 109),
    "IT" => array("name" => "Italy", "id" => 110),
    "JM" => array("name" => "Jamaica", "id" => 111),
    "JP" => array("name" => "Japan", "id" => 112),
    "JE" => array("name" => "Jersey", "id" => 113),
    "JO" => array("name" => "Jordan", "id" => 114),
    "KZ" => array("name" => "Kazakhstan", "id" => 115),
    "KE" => array("name" => "Kenya", "id" => 116),
    "KI" => array("name" => "Kiribati", "id" => 117),
    "KP" => array("name" => "Korea, Democratic People's Republic of", "id" => 118),
    "KR" => array("name" => "Korea, Republic of", "id" => 119),
    "XK" => array("name" => "Kosovo", "id" => 120),
    "KW" => array("name" => "Kuwait", "id" => 121),
    "KG" => array("name" => "Kyrgyzstan", "id" => 122),
    "LA" => array("name" => "Lao People's Democratic Republic", "id" => 123),
    "LV" => array("name" => "Latvia", "id" => 124),
    "LB" => array("name" => "Lebanon", "id" => 125),
    "LS" => array("name" => "Lesotho", "id" => 126),
    "LR" => array("name" => "Liberia", "id" => 127),
    "LY" => array("name" => "Libyan Arab Jamahiriya", "id" => 128),
    "LI" => array("name" => "Liechtenstein", "id" => 129),
    "LT" => array("name" => "Lithuania", "id" => 130),
    "LU" => array("name" => "Luxembourg", "id" => 131),
    "MO" => array("name" => "Macao", "id" => 132),
    "MK" => array("name" => "Macedonia, the Former Yugoslav Republic of", "id" => 133),
    "MG" => array("name" => "Madagascar", "id" => 134),
    "MW" => array("name" => "Malawi", "id" => 135),
    "MY" => array("name" => "Malaysia", "id" => 136),
    "MV" => array("name" => "Maldives", "id" => 137),
    "ML" => array("name" => "Mali", "id" => 138),
    "MT" => array("name" => "Malta", "id" => 139),
    "MH" => array("name" => "Marshall Islands", "id" => 140),
    "MQ" => array("name" => "Martinique", "id" => 141),
    "MR" => array("name" => "Mauritania", "id" => 142),
    "MU" => array("name" => "Mauritius", "id" => 143),
    "YT" => array("name" => "Mayotte", "id" => 144),
    "MX" => array("name" => "Mexico", "id" => 145),
    "FM" => array("name" => "Micronesia, Federated States of", "id" => 146),
    "MD" => array("name" => "Moldova, Republic of", "id" => 147),
    "MC" => array("name" => "Monaco", "id" => 148),
    "MN" => array("name" => "Mongolia", "id" => 149),
    "ME" => array("name" => "Montenegro", "id" => 150),
    "MS" => array("name" => "Montserrat", "id" => 151),
    "MA" => array("name" => "Morocco", "id" => 152),
    "MZ" => array("name" => "Mozambique", "id" => 153),
    "MM" => array("name" => "Myanmar", "id" => 154),
    "NA" => array("name" => "Namibia", "id" => 155),
    "NR" => array("name" => "Nauru", "id" => 156),
    "NP" => array("name" => "Nepal", "id" => 157),
    "NL" => array("name" => "Netherlands", "id" => 158),
    "AN" => array("name" => "Netherlands Antilles", "id" => 159),
    "NC" => array("name" => "New Caledonia", "id" => 160),
    "NZ" => array("name" => "New Zealand", "id" => 161),
    "NI" => array("name" => "Nicaragua", "id" => 162),
    "NE" => array("name" => "Niger", "id" => 163),
    "NG" => array("name" => "Nigeria", "id" => 164),
    "NU" => array("name" => "Niue", "id" => 165),
    "NF" => array("name" => "Norfolk Island", "id" => 166),
    "MP" => array("name" => "Northern Mariana Islands", "id" => 167),
    "NO" => array("name" => "Norway", "id" => 168),
    "OM" => array("name" => "Oman", "id" => 169),
    "PK" => array("name" => "Pakistan", "id" => 170),
    "PW" => array("name" => "Palau", "id" => 171),
    "PS" => array("name" => "Palestinian Territory, Occupied", "id" => 172),
    "PA" => array("name" => "Panama", "id" => 173),
    "PG" => array("name" => "Papua New Guinea", "id" => 174),
    "PY" => array("name" => "Paraguay", "id" => 175),
    "PE" => array("name" => "Peru", "id" => 176),
    "PH" => array("name" => "Philippines", "id" => 177),
    "PN" => array("name" => "Pitcairn", "id" => 178),
    "PL" => array("name" => "Poland", "id" => 179),
    "PT" => array("name" => "Portugal", "id" => 180),
    "PR" => array("name" => "Puerto Rico", "id" => 181),
    "QA" => array("name" => "Qatar", "id" => 182),
    "RE" => array("name" => "Reunion", "id" => 183),
    "RO" => array("name" => "Romania", "id" => 184),
    "RU" => array("name" => "Russian Federation", "id" => 185),
    "RW" => array("name" => "Rwanda", "id" => 186),
    "BL" => array("name" => "Saint Barthelemy", "id" => 187),
    "SH" => array("name" => "Saint Helena", "id" => 188),
    "KN" => array("name" => "Saint Kitts and Nevis", "id" => 189),
    "LC" => array("name" => "Saint Lucia", "id" => 190),
    "MF" => array("name" => "Saint Martin", "id" => 191),
    "PM" => array("name" => "Saint Pierre and Miquelon", "id" => 192),
    "VC" => array("name" => "Saint Vincent and the Grenadines", "id" => 193),
    "WS" => array("name" => "Samoa", "id" => 194),
    "SM" => array("name" => "San Marino", "id" => 195),
    "ST" => array("name" => "Sao Tome and Principe", "id" => 196),
    "SA" => array("name" => "Saudi Arabia", "id" => 197),
    "SN" => array("name" => "Senegal", "id" => 198),
    "RS" => array("name" => "Serbia", "id" => 199),
    "CS" => array("name" => "Serbia and Montenegro", "id" => 200),
    "SC" => array("name" => "Seychelles", "id" => 201),
    "SL" => array("name" => "Sierra Leone", "id" => 202),
    "SG" => array("name" => "Singapore", "id" => 203),
    "SX" => array("name" => "St Martin", "id" => 204),
    "SK" => array("name" => "Slovakia", "id" => 205),
    "SI" => array("name" => "Slovenia", "id" => 206),
    "SB" => array("name" => "Solomon Islands", "id" => 207),
    "SO" => array("name" => "Somalia", "id" => 208),
    "ZA" => array("name" => "South Africa", "id" => 209),
    "GS" => array("name" => "South Georgia and the South Sandwich Islands", "id" => 210),
    "SS" => array("name" => "South Sudan", "id" => 211),
    "ES" => array("name" => "Spain", "id" => 212),
    "LK" => array("name" => "Sri Lanka", "id" => 213),
    "SD" => array("name" => "Sudan", "id" => 214),
    "SR" => array("name" => "Suriname", "id" => 215),
    "SJ" => array("name" => "Svalbard and Jan Mayen", "id" => 216),
    "SZ" => array("name" => "Swaziland", "id" => 217),
    "SE" => array("name" => "Sweden", "id" => 218),
    "CH" => array("name" => "Switzerland", "id" => 219),
    "SY" => array("name" => "Syrian Arab Republic", "id" => 220),
    "TW" => array("name" => "Taiwan, Province of China", "id" => 221),
    "TJ" => array("name" => "Tajikistan", "id" => 222),
    "TZ" => array("name" => "Tanzania, United Republic of", "id" => 223),
    "TH" => array("name" => "Thailand", "id" => 224),
    "TL" => array("name" => "Timor-Leste", "id" => 225),
    "TG" => array("name" => "Togo", "id" => 226),
    "TK" => array("name" => "Tokelau", "id" => 227),
    "TO" => array("name" => "Tonga", "id" => 228),
    "TT" => array("name" => "Trinidad and Tobago", "id" => 229),
    "TN" => array("name" => "Tunisia", "id" => 230),
    "TR" => array("name" => "Turkey", "id" => 231),
    "TM" => array("name" => "Turkmenistan", "id" => 232),
    "TC" => array("name" => "Turks and Caicos Islands", "id" => 233),
    "TV" => array("name" => "Tuvalu", "id" => 234),
    "UG" => array("name" => "Uganda", "id" => 235),
    "UA" => array("name" => "Ukraine", "id" => 236),
    "AE" => array("name" => "United Arab Emirates", "id" => 237),
    "GB" => array("name" => "United Kingdom", "id" => 238),
    "US" => array("name" => "United States", "id" => 239),
    "UM" => array("name" => "United States Minor Outlying Islands", "id" => 240),
    "UY" => array("name" => "Uruguay", "id" => 241),
    "UZ" => array("name" => "Uzbekistan", "id" => 242),
    "VU" => array("name" => "Vanuatu", "id" => 243),
    "VE" => array("name" => "Venezuela", "id" => 244),
    "VN" => array("name" => "Viet Nam", "id" => 245),
    "VG" => array("name" => "Virgin Islands, British", "id" => 246),
    "VI" => array("name" => "Virgin Islands, U.s.", "id" => 247),
    "WF" => array("name" => "Wallis and Futuna", "id" => 248),
    "EH" => array("name" => "Western Sahara", "id" => 249),
    "YE" => array("name" => "Yemen", "id" => 250),
    "ZM" => array("name" => "Zambia", "id" => 251),
    "ZW" => array("name" => "Zimbabwe", "id" => 252)
);
?>